__all__ = ['BOOL_KIND', 'INT_KIND', 'UINT_KIND', 'REAL_KIND', 'COMPLEX_KIND',
    'STRING_KIND', 'BYTES_KIND', 'VOID_KIND', 'DATETIME_KIND',
    'UNIFORM_DIM_KIND', 'STRUCT_KIND', 'EXPRESSION_KIND',
    'UNINITIALIZED_TYPE_ID', 'BOOL_TYPE_ID',
    'INT8_TYPE_ID', 'INT16_TYPE_ID', 'INT32_TYPE_ID', 'INT64_TYPE_ID',
    'UINT8_TYPE_ID', 'UINT16_TYPE_ID', 'UINT32_TYPE_ID', 'UINT64_TYPE_ID',
    'FLOAT32_TYPE_ID', 'FLOAT64_TYPE_ID',
    'COMPLEX_FLOAT32_TYPE_ID', 'COMPLEX_FLOAT64_TYPE_ID',
    'VOID_TYPE_ID', 'VOID_POINTER_TYPE_ID',
    'POINTER_TYPE_ID', 'BYTES_TYPE_ID', 'FIXEDBYTES_TYPE_ID',
    'STRING_TYPE_ID', 'FIXEDSTRING_TYPE_ID',
    'CATEGORICAL_TYPE_ID', 'DATE_TYPE_ID', 'BUSDATE_TYPE_ID',
    'JSON_TYPE_ID', 'STRIDED_DIM_TYPE_ID', 'FIXED_DIM_TYPE_ID',
    'OFFSET_DIM_TYPE_ID', 'VAR_DIM_TYPE_ID', 'STRUCT_TYPE_ID',
    'FIXEDSTRUCT_TYPE_ID', 'TUPLE_TYPE_ID', 'NDOBJECT_TYPE_ID',
    'CONVERT_TYPE_ID', 'BYTESWAP_TYPE_ID', 'VIEW_TYPE_ID',
    'PROPERTY_TYPE_ID', 'EXPR_TYPE_ID', 'UNARY_EXPR_TYPE_ID',
    'GROUPBY_TYPE_ID', 'DTYPE_TYPE_ID',
    'BUILTIN_TYPE_ID_COUNT'
    ]

BOOL_KIND = 0
INT_KIND = 1
UINT_KIND = 2
REAL_KIND = 3
COMPLEX_KIND = 4
STRING_KIND = 5
BYTES_KIND = 6
VOID_KIND = 7
DATETIME_KIND = 8
UNIFORM_DIM_KIND = 9
STRUCT_KIND = 10
EXPRESSION_KIND = 11

UNINITIALIZED_TYPE_ID = 0
BOOL_TYPE_ID = 1
INT8_TYPE_ID = 2
INT16_TYPE_ID = 3
INT32_TYPE_ID = 4
INT64_TYPE_ID = 5
UINT8_TYPE_ID = 6
UINT16_TYPE_ID = 7
UINT32_TYPE_ID = 8
UINT64_TYPE_ID = 9
FLOAT32_TYPE_ID = 10
FLOAT64_TYPE_ID = 11
COMPLEX_FLOAT32_TYPE_ID = 12
COMPLEX_FLOAT64_TYPE_ID = 13
VOID_TYPE_ID = 14
VOID_POINTER_TYPE_ID = 15
POINTER_TYPE_ID = 16
BYTES_TYPE_ID = 17
FIXEDBYTES_TYPE_ID = 18
STRING_TYPE_ID = 19
FIXEDSTRING_TYPE_ID = 20
CATEGORICAL_TYPE_ID = 21
DATE_TYPE_ID = 22
BUSDATE_TYPE_ID = 23
JSON_TYPE_ID = 24
STRIDED_DIM_TYPE_ID = 25
FIXED_DIM_TYPE_ID = 26
OFFSET_DIM_TYPE_ID = 27
VAR_DIM_TYPE_ID = 28
STRUCT_TYPE_ID = 29
FIXEDSTRUCT_TYPE_ID = 30
TUPLE_TYPE_ID = 31
NDOBJECT_TYPE_ID = 32
CONVERT_TYPE_ID = 33
BYTESWAP_TYPE_ID = 34
VIEW_TYPE_ID = 35
PROPERTY_TYPE_ID = 36
EXPR_TYPE_ID = 37
UNARY_EXPR_TYPE_ID = 38
GROUPBY_TYPE_ID = 39
DTYPE_TYPE_ID = 40

BUILTIN_TYPE_ID_COUNT = 15
