__all__ = ['BOOL', 'INT', 'UINT', 'REAL', 'COMPLEX',
    'STRING', 'BYTES', 'VOID', 'DATETIME',
    'UNIFORM_DIM', 'STRUCT', 'EXPRESSION',
    ]

BOOL = 0
INT = 1
UINT = 2
REAL = 3
COMPLEX = 4
CHAR = 5
STRING = 6
BYTES = 7
VOID = 8
DATETIME = 9
UNIFORM_DIM = 10
STRUCT = 11
EXPRESSION = 12
