__all__ = ['BOOL', 'INT', 'UINT', 'REAL', 'COMPLEX',
    'STRING', 'BYTES', 'VOID', 'DATETIME',
    'DIM', 'STRUCT', 'TUPLE', 'DYNAMIC', 'EXPR', 'OPTION',
    'MEMORY', 'FUNCTION', 'SYMBOLIC', 'CUSTOM'
    ]

BOOL = 0
INT = 1
UINT = 2
REAL = 3
COMPLEX = 4
CHAR = 5
STRING = 6
BYTES = 7
VOID = 8
DATETIME = 9
DIM = 10
STRUCT = 11
TUPLE = 12
DYNAMIC = 13
EXPR = 14
OPTION = 15
MEMORY = 16
FUNCTION = 17
SYMBOLIC = 18
CUSTOM = 19
