__all__ = ['BOOL_KIND', 'INT_KIND', 'UINT_KIND', 'REAL_KIND', 'COMPLEX_KIND',
    'STRING_KIND', 'BYTES_KIND', 'VOID_KIND', 'DATETIME_KIND',
    'UNIFORM_DIM_KIND', 'STRUCT_KIND', 'EXPRESSION_KIND',
    'UNINITIALIZED_TYPE_ID', 'BOOL_TYPE_ID',
    'INT8_TYPE_ID', 'INT16_TYPE_ID', 'INT32_TYPE_ID', 'INT64_TYPE_ID', 'INT128_TYPE_ID',
    'UINT8_TYPE_ID', 'UINT16_TYPE_ID', 'UINT32_TYPE_ID', 'UINT64_TYPE_ID', 'UINT128_TYPE_ID',
    'FLOAT16_TYPE_ID', 'FLOAT32_TYPE_ID', 'FLOAT64_TYPE_ID', 'FLOAT128_TYPE_ID',
    'COMPLEX_FLOAT32_TYPE_ID', 'COMPLEX_FLOAT64_TYPE_ID',
    'VOID_TYPE_ID', 'VOID_POINTER_TYPE_ID',
    'POINTER_TYPE_ID', 'BYTES_TYPE_ID', 'FIXEDBYTES_TYPE_ID',
    'STRING_TYPE_ID', 'FIXEDSTRING_TYPE_ID',
    'CATEGORICAL_TYPE_ID', 'DATE_TYPE_ID', 'BUSDATE_TYPE_ID',
    'JSON_TYPE_ID', 'STRIDED_DIM_TYPE_ID', 'FIXED_DIM_TYPE_ID',
    'OFFSET_DIM_TYPE_ID', 'VAR_DIM_TYPE_ID', 'STRUCT_TYPE_ID',
    'FIXEDSTRUCT_TYPE_ID', 'TUPLE_TYPE_ID', 'NDOBJECT_TYPE_ID',
    'CONVERT_TYPE_ID', 'BYTESWAP_TYPE_ID', 'VIEW_TYPE_ID',
    'PROPERTY_TYPE_ID', 'EXPR_TYPE_ID', 'UNARY_EXPR_TYPE_ID',
    'GROUPBY_TYPE_ID', 'DTYPE_TYPE_ID',
    'BUILTIN_TYPE_ID_COUNT'
    ]

BOOL_KIND = 0
INT_KIND = 1
UINT_KIND = 2
REAL_KIND = 3
COMPLEX_KIND = 4
STRING_KIND = 5
BYTES_KIND = 6
VOID_KIND = 7
DATETIME_KIND = 8
UNIFORM_DIM_KIND = 9
STRUCT_KIND = 10
EXPRESSION_KIND = 11

UNINITIALIZED_TYPE_ID = 0
BOOL_TYPE_ID = 1
INT8_TYPE_ID = 2
INT16_TYPE_ID = 3
INT32_TYPE_ID = 4
INT64_TYPE_ID = 5
INT128_TYPE_ID = 6
UINT8_TYPE_ID = 7
UINT16_TYPE_ID = 8
UINT32_TYPE_ID = 9
UINT64_TYPE_ID = 10
UINT128_TYPE_ID = 11
FLOAT16_TYPE_ID = 12
FLOAT32_TYPE_ID = 13
FLOAT64_TYPE_ID = 14
FLOAT128_TYPE_ID = 15
COMPLEX_FLOAT32_TYPE_ID = 16
COMPLEX_FLOAT64_TYPE_ID = 17
VOID_TYPE_ID = 18
VOID_POINTER_TYPE_ID = 19
POINTER_TYPE_ID = 20
BYTES_TYPE_ID = 21
FIXEDBYTES_TYPE_ID = 22
STRING_TYPE_ID = 23
FIXEDSTRING_TYPE_ID = 24
CATEGORICAL_TYPE_ID = 25
DATE_TYPE_ID = 26
DATETIME_TYPE_ID = 27
BUSDATE_TYPE_ID = 28
JSON_TYPE_ID = 29
STRIDED_DIM_TYPE_ID = 30
FIXED_DIM_TYPE_ID = 31
OFFSET_DIM_TYPE_ID = 32
VAR_DIM_TYPE_ID = 33
STRUCT_TYPE_ID = 34
FIXEDSTRUCT_TYPE_ID = 35
TUPLE_TYPE_ID = 36
NDOBJECT_TYPE_ID = 37
CONVERT_TYPE_ID = 38
BYTESWAP_TYPE_ID = 39
VIEW_TYPE_ID = 40
PROPERTY_TYPE_ID = 41
EXPR_TYPE_ID = 42
UNARY_EXPR_TYPE_ID = 43
GROUPBY_TYPE_ID = 44
DTYPE_TYPE_ID = 45

BUILTIN_TYPE_ID_COUNT = 19
