#!/bin/bash
#
#
# Copyright (C) 2011-13, DyND Developers
# BSD 2-Clause License, see LICENSE.txt
#
#
#
# This is the master linux/osx build + test script for building
# the dynd python bindings on jenkins.
#
# Jenkins Requirements:
#   - Anaconda should be installed in ~/anaconda
#   - Use a jenkins build matrix for multiple
#     platforms/python versions
#   - Use the XShell plugin to launch this script
#   - Call the script from the root workspace
#     directory as ./jenkins/jenkins-build
#

# Require a version of Python to be selected
if [ "${PYTHON_VERSION}" == "" ]; then
 echo You must select a Python version with the PYTHON_VERSION variable.
 exit 1
fi

# Remove the build subdirectory from last time
rm -rf build

# Get libdynd into the libraries subdirectory
# TODO: Build libdynd in a separate jenkins project,
#       and use its build artifact here.
./jenkins/checkout_libdynd.sh || exit 1

# Use conda to create a conda environment of the required
# python version and containing the dependencies.
export PYENV_PREFIX=${WORKSPACE}/build/pyenv
./jenkins/create_conda_pyenv.sh ${PYTHON_VERSION} ${PYENV_PREFIX} || exit 1
export PATH=${PYENV_PREFIX}/bin:${PATH}

if [ -f "${PYENV_PREFIX}/bin/python" ]; then
 export PYTHON_EXECUTABLE=${PYENV_PREFIX}/bin/python
elif [ -f "${PYENV_PREFIX}/bin/python3" ]; then
 export PYTHON_EXECUTABLE=${PYENV_PREFIX}/bin/python3
else
 echo Conda environment creation failed.
 exit 1
fi

# Create a fresh makefile with cmake, and do the build/install
cd build
cmake -DCMAKE_INSTALL_PREFIX=${PYENV_PREFIX} -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} .. || exit 1
make -j5 || exit 1
make install || exit 1

# Run the unit tests
${PYENV_PREFIX}/bin/python -c 'import dynd;dynd.test(xunitfile="../test_results.xml", exit=1)' || exit 1

# Retrieve the version number
export PYDYND_VERSION=`${PYENV_PREFIX}/bin/python -c 'import dynd;print(dynd.__version_string__)'`
export PYDYND_VERSION=${PYDYND_VERSION//-/_}
export PYDYND_VERSION=${PYDYND_VERSION:1}

# Put the conda package by itself in the directory pkgs
cd ..
rm -rf pkgs
mkdir pkgs
cd pkgs

# Create a conda package from the build
~/anaconda/bin/conda package -p ${PYENV_PREFIX} --pkg-name=dynd-python --pkg-version=${PYDYND_VERSION} || exit 1

cd ..